### ISSUE TITLE
Search input need double press

### ISSUE THREAD

**Issue by romanrast** [djett41/ionic-filter-bar#13] opened 2015-07-08 18:24 UTC
To enter a search string I need to double press into the input field. After the second click into the input field the keyboard is shown and the input field is focused. Does anyone else see this too? (running on iOS 8.4)

**Comment by gigocabrera** [comment] 2015-07-08 21:25
I noticed the same behavior. But maybe an auto-focus functionality would be a better solution, saving one (possibly two) taps/clicks.

**Comment by djett41** [comment] 2015-07-08 22:03
Interesting, so if I understand you correctly, when you click the search icon, and the filter bar slides in, the keyboard isnt automatically coming up?  On my app the input is autofocused and the keyboard/filter-bar slide in at the exact same time.  I have an iphone 6 still on ios 8.1.1 though.

I can check it out and see what could be different.  @gigocabrera which device do you have?

**Comment by romanrast** [comment] 2015-07-08 22:32
Exactly, by clicking on the search icon the keyboard doesnt come up. I'm using an iPhone 6 iOS 8.4. I see the same behavior on the xcode simulator.

**Comment by djett41** [comment] 2015-07-08 22:41
Ok thanks.  I just ran on simulator using 8.2 and didnt see the same behavior, the keyboard came right up.  Same with android.  I'll upgrade to 8.4 a little later and check it out.  Also are you running the demo? Also can you check to see if this is present in chrome too via ionic serve?

By the way are you using the ionic keyboard plugin?  Not sure if it will make a difference for this issue, but fr best results the ionic keyboard should be set to 
    window.cordova.plugins.Keyboard.disableScroll(true); 

in the run module.  I'll update the demo and docs as well, but this may not apply to your issue.

**Comment by romanrast** [comment] 2015-07-08 23:01
I tried it in chrome with ionic serve --lab, works fine the auto-focus catches (since we don't have a digital keyboard here).
I'm using the ionic keyboard plugin and I'm setting cordova.plugins.Keyboard.hideKeyboardAccessoryBar(false); 
I also tried cordova.plugins.Keyboard.disableScroll(true); but this had no effect, also setting the AccessoryBar to false didn't change anything. Hope it's not my wrong implementation. I will try your demo tomorrow.

**Comment by djett41** [comment] 2015-07-09 03:12
Ok great.  Sure try the demo with your Dev setup (in the mean time, you will need to add the ionic keyboard plugin and place those settings in a run block for the app.js I will add that stuff to the demo this weekend).  Let me know what you get, if youre still running into an issue and have a setup that I can replicate, I can find a fix this weekend.

Thanks!

**Comment by gigocabrera** [comment] 2015-07-10 19:49
Hi @djett41 I am using iOS 8.4 and I have a setup that you can use to test this issue. Open Ionic View and open Preview Shared App. Enter App ID 97f24c2e. This will load MoneyLeash on your phone. The login credentials are included and hard coded (still as a prototype). Once logged in, on the left menu select Accounts --> 1Personal and you should see the search icon at the top on the header.
The project lives here if you want to see the actual code
https://github.com/gigocabrera/moneyleash

**Comment by gigocabrera** [comment] 2015-07-10 19:54
@djett41 by the way, we met before. Thanks again for your help!!!
http://forum.ionicframework.com/t/swipe-in-ion-list-not-working-like-ios-swipe-feature/20903

**Comment by djett41** [comment] 2015-07-13 12:36
Thanks buddy! @gigocabrera Sorry I did an upgrade to cordova 5 over the weekend and hosed my environment :-( finally back up and running so I can look at this either today or tomorrow.  Thanks for providing the detailed info!

**Comment by romanrast** [comment] 2015-07-13 16:49
@gigocabrera I tried your app over ionic view. The search input needs double tap there aswell. Tested on iOS8.4 iPhone6

**Comment by gigocabrera** [comment] 2015-07-14 14:38
@romanrast that's great news. At least the issue is consistent.

**Comment by djett41** [comment] 2015-07-15 15:59
Thanks guys, will look into this soon!

**Comment by gigocabrera** [comment] 2015-07-15 16:05
New discovery. After changing the transactions view from collection-repeat to ng-repeat (testing performance) I got the search to automatically auto-focus with only one tap. I saw it happened twice but unfortunately it went back to 2 taps and no auto-focus. Not sure if this helps.

**Comment by djett41** [comment] 2015-07-15 16:47
@romanrast @gigocabrera what ionic UI version are you guys using?

**Comment by romanrast** [comment] 2015-07-15 16:58
I'll have a look. I think it's the latest version vanadium vaquita 1.0.1

**Comment by gigocabrera** [comment] 2015-07-15 17:55
My ionic info shows this:
Cordova CLI: 5.1.1
Ionic CLI Version: 1.6.1
Ionic App Lib Version: 0.3.3
Node Version: v0.12.7
and vanadium vaquita v1.0.1

**Comment by djett41** [comment] 2015-07-16 02:09
Ok So I 
1. Changed the demo to 1.0.1 ionic ui version
2. Downloaded @gigocabrera code, ran on ios emulator
3. Downladed @gigocabrera 's app via Ionic View

And all of them autofocused haha..

Since my iphone 6 is still on ios 8.1, and my macbook pro is kinda old and still on Mavericks with Xcode 6.2 (app gets built with 8.2 sdk), I'm guessing that this is related to ios 8.4, which means I will need to update either my phone or macbook to Yosemite / Xcode 6.4 and replicate it.

What's also weird is that my boy is developing an app with me has the app built on his iPhone 6 which is running ios 9.3 beta and built with target 9, Xcode 6.4 7beta and the filter bar autofocuses.

So I'm going to give ios 8.4 a go so I can see what's going on.  I will keep one at 8.1/8.2 so I can test backward compatibility if I find a fix.

**Comment by djett41** [comment] 2015-07-16 03:33
@gigocabrera I updated my iPhone6 and I cna finally replicate it on your app on Ionic View.  I used my app as well but mine filter bar autofocuses, so I'm thinking it may be something in the code that may be conflicting.  In order for me to mess with it I'm going to have to upgrade my OS to Yosemite and upgrade to Xcode 6.4 which will be in the next day or so.

In the meantime, Can you try removing the filter:searchText on your transactions ng-repeat?  I don't see a searchText property defined anywhere on your scope and I'm wondering if that's conflicting with the filterBar.  Even if that filter isn't causing an issue, it's very possible that one (or more) of the other filters applied are causing this.  (havent tried with multiple filters, but honestly I usually filter in the controller to increase performance.  HTML filters can cause performance issues since the digest cylce will cause them to run multiple times)  .  But it's possible that one of the other filters could be taking the focus away from the filterBar filter.  Again once I upgrade my macbook I can play around with it.

@romanrast can you post your HTML?

**Comment by gigocabrera** [comment] 2015-07-16 18:43
@djett41 I removed all the filters and the issue persists in Ionic View. I went from 

```
<div ng-repeat="transaction in transactions | reverselist | filter:searchText | groupByDayMonthYear" divider-collection-repeat>
```

to

```
<div ng-repeat="transaction in transactions>
```

On a separate note, you mentioned 

> I usually filter in the controller to increase performance.

Where can I learn how to filter in the controller? For example, how can I 'reverse' the list of transactions so they show the must recent at the top without having the use the reverselist filter in HTML as I'm doing now?

**Comment by djett41** [comment] 2015-07-18 00:45
Cool I'm updating my MAC overnight so I can play with it this weekend.  As far as the filters, this is a good read that explains how the digest loop affects DOM filters.  You can even do a self check by just adding a console log in your filter and watch how many times it gets called.  You will notice tht it gets called alot more times than you would expect.

https://www.binpress.com/tutorial/speeding-up-angular-js-with-simple-optimizations/135

**Comment by djett41** [comment] 2015-07-18 02:01
@gigocabrera add the following to your config.xml.  If this works I'll update the docs but this preference allows .focus() to bring up the keyboard which is what the plugin does.  Perhaps something changed in ios as of 8.4 in which this is required.  I have had this in my app for a while.  Hope this works!

```
<preference name="KeyboardDisplayRequiresUserAction" value="false"/>
```

https://cordova.apache.org/docs/en/5.1.1/guide_platforms_ios_config.md.html

**Comment by gigocabrera** [comment] 2015-07-18 03:14
@djett41 I added the preference to the config.xml in the root folder of my app and that didn't work. Then I added the same to the config.xml under 'moneyleash\platforms\ios\MoneyLeash' and that didn't work either. HOWEVER, if I play with the search for a while, tapping various parts of the screen and then the search, I get it to work half the time. I haven't figure out exactly what pattern makes it work but I do see it. It is most likely an issue on my view, controller or my design (CSS?), not sure. 

If you download my app again, please make sure you Sync to Latest.

BTW, thanks for the link !!!

**Comment by djett41** [comment] 2015-07-18 03:35
@gigocabrera Im starting to think this is an issue related to Ionic View.  I just uploaded this plugin to the Ionic Marketplace and made an Ionic View app with id ab56e8bd and not only is the autofocus not working, but the keyboard accessory bar is not hidden when I'm now hiding it!  On emulator works fine, unfortunately I need to wait until I update my OS to run on my phone again since new Xcode isnt avail for Mavericks.

Can you try on your physical device?

I also added config to change the status bar to white, which happens on emulator but not on Ionic View, so theres definitely something funny with Ionic View and plugins

**Comment by gigocabrera** [comment] 2015-07-18 18:29
@djett41 I tried your app on my iPhone and I get the same result. As you mentioned, it is probably related to the Ionic View. Btw, I also tried changing the status bar to white and could not get it to work. I even tried modifying the iOS files under platform directly to no avail, so there's definitely something going on with the ionic view.

Should we reach out to the Ionic Team?

**Comment by djett41** [comment] 2015-07-19 09:13
@gigocabrera it doesn't look like the status bar plugin is supported by Ionic View so I'm not worried about that one.  However the Keyboard plugin is supposed to be supported so I put in an issue [here](https://github.com/driftyco/ionic-view-issues/issues/125) for Ionic View .  I am going to close this issue since it's related to Ionic View, but I'll reopen if anything else comes up that may be the fault of Ionic Filter Bar.  Thanks again!!

**Closed as completed by djett41** 2015-07-19 09:13 UTC
Labels: invalid

**Comment by constantinoantunes** [comment] 2015-11-15 17:50
Hi,
I was having the same issue romanrast refers in the first comment. The problem was happening on iOS versions 6 and 9. What ended up working for me was moving the KeyboardDisplayRequiresUserAction preference to the config.xml root.

**Comment by farukkaya** [comment] 2016-11-28 09:39
@romanrast @djett41 How did you fix this error
I'm having the same problem, Could you help
APPID: 61a6461b
